version: '3.4'

services:
  api:
    image: downloader-api
    depends_on:
      - redis
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    env_file: ./.env
    volumes:
      - .:/usr/app
    environment:
      NODE_ENV: production
      REDIS_URL: redis://127.0.0.1:6379
      REMOTE_BROWSER_ENDPOINT1: http://localhost:5000
      REMOTE_BROWSER_TABS_COUNT1: 5
      DISABLE_CRAWLER: 'false'
      CRAWLER_CONCURRENCY: 17
      PAUSE_CRAWLER_ON_HIGH_LOAD: 'true'
      CRAWLER_TOTAL_MEMORY: 1024
      CRAWLER_PAUSE_DURATION_LIMIT: 10
      TOTAL_DISK_SPACE: 1024
      CORS_ALLOWED_ORIGINS: https://www.movietracker.mom --- https://movietracker.mom --- https://admin.movietracker.mom
      MAILSERVER_HOST: localhost
      MAILSERVER_PORT: 587
      MAILSERVER_USERNAME: webmaster@movietracker.mom
    #    ports:
#      - "3000:3000"
    deploy:
      resources:
        #also check --max_old_space_size in Dockerfile
        limits:
          cpus: "0.5"
          memory: 1224M
        reservations:
          cpus: "0.2"
          memory: 300M
    restart: always
    healthcheck:
      test: [ "CMD", "node", "healthcheck.js" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: "redis:alpine"
    network_mode: host
    env_file: ./.env
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - USE_OPTIMIZATION=true
#    ports:
#      - "6379:6379"
    volumes:
      - redis:/data
    entrypoint: /bin/sh -c "redis-server --latency-monitor-threshold 100 --maxmemory 200mb --maxmemory-policy allkeys-lfu --save 60 1 --appendonly yes --requirepass $$REDIS_PASSWORD"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 210M
        reservations:
          cpus: "0.05"
          memory: 50M
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 20s

  remoteBrowser:
    image: ashkanaz2828/downloader_remotebrowser
    network_mode: host
    env_file: ./remotebrowser.env
    environment:
      - NODE_ENV=development
      - CRAWLER_BROWSER_TAB_COUNT=5
      - TOTAL_MEMORY_AMOUNT=1024
      - TOTAL_DISK_SPACE=2000
      - SERVER_NAME=remoteBrowser-vps-1
      - PRINT_ERRORS=true
      - CRAWLER_PAUSE_DURATION_LIMIT=30
      - DISABLE_UPLOAD_JOB=false
      - BLACKHOLE_FILE_SIZE_LIMIT=768
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1000M
        reservations:
          memory: 300M
#    volumes:
#      - ./:/usr/app
#    ports:
#      - "5000:5000"
    restart: always

  telegrambot:
    image: ashkanaz2828/python-telegrambot-docker
    network_mode: host
    depends_on:
      - api
    env_file: ./telegrambot.env
    environment:
      - SERVER_ADDRESS=https://api.movietracker.mom
    volumes:
      - telegrambot
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 150M
        reservations:
          memory: 50M
    restart: always

  adminpanel:
    image: ashkanaz2828/downloader_adminpanel
    network_mode: host
    depends_on:
      - api
    environment:
      - REACT_APP_BASE_URL=https://api.movietracker.mom
#    ports:
#      - "7070:7070"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 200M
        reservations:
          memory: 50M
    restart: unless-stopped

  website:
    image: ashkanaz2828/downloader_website
    network_mode: host
    depends_on:
      - api
    environment:
      - REACT_APP_BASE_URL=https://api.movietracker.mom
#    ports:
#      - "9090:9090"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 300M
        reservations:
          memory: 50M
    restart: unless-stopped

  nginx:
    network_mode: host
    build: ./nginx
#    ports:
#      - '80:80'
    depends_on:
      - api
      - telegrambot
      - adminpanel
      - website

  #more details in readme.md
  mailServer:
    image: boky/postfix
#    network_mode: host
    environment:
      - ALLOWED_SENDER_DOMAINS=movietracker.mom
    ports:
      - "587:587"
      - "25:25"
#    volumes:
#      - ./postfix/main.cf:/etc/postfix/main.cf
#      - ./postfix/virtual:/etc/postfix/virtual
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 300M
        reservations:
          memory: 50M
    restart: always

volumes:
  redis:
    driver: local
  telegrambot:
    driver: local