version: '3.4'

services:
  api:
    image: downloader-api
    depends_on:
      - redis
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    env_file: ./.env
    volumes:
      - .:/usr/app
    environment:
      NODE_ENV: production
      REDIS_URL: redis://127.0.0.1:6379
#    ports:
#      - "3000:3000"
    deploy:
      resources:
        #also check --max_old_space_size in Dockerfile
        limits:
          cpus: 0.5
          memory: 1224M
        reservations:
          cpus: 0.2
          memory: 300M
    restart: always
    healthcheck:
      test: [ "CMD", "node", "healthcheck.js" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s


  redis:
    image: "redis:alpine"
    network_mode: host
    env_file: ./.env
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - USE_OPTIMIZATION=true
#    ports:
#      - "6379:6379"
    volumes:
      - redis:/data
    entrypoint: /bin/sh -c "redis-server --latency-monitor-threshold 100 --maxmemory 200mb --maxmemory-policy allkeys-lfu --save 60 1 --appendonly yes --requirepass $$REDIS_PASSWORD"
    deploy:
      resources:
        limits:
          cpus: 0.3
          memory: 210M
        reservations:
          cpus: 0.05
          memory: 50M
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 20s

  telegrambot:
    image: ashkanaz2828/python-telegrambot-docker
    network_mode: host
    depends_on:
      - api
    env_file: ./telegrambot.env
    environment:
      - SERVER_ADDRESS=http://localhost:8080/api
    volumes:
      - telegrambot
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 150M
        reservations:
          memory: 50M
    restart: always

  adminpanel:
    image: ashkanaz2828/downloader_adminpanel
    network_mode: host
    depends_on:
      - api
    environment:
      - REACT_APP_BASE_URL=http://localhost:8080/api
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 200M
        reservations:
          memory: 50M
    restart: unless-stopped

  nginx:
    network_mode: host
    build: ./nginx
#    ports:
#      - '8080:8080'
    depends_on:
      - api
      - telegrambot
      - adminpanel

volumes:
  redis:
    driver: local
  telegrambot:
    driver: local