version: '3.4'

services:
  api:
    image: downloader-api
    depends_on:
      - redis
      - rabbitmq
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    env_file: ./env/.env
    volumes:
      - .:/usr/app
      - ./db-backups:/db-backups
    environment:
      NODE_ENV: production
      REDIS_URL: redis://127.0.0.1:6379
      DISABLE_CRAWLER: 'false'
      DISABLE_TORRENT_CRAWLER: 'false'
      CRAWLER_CONCURRENCY: 13
      PAUSE_CRAWLER_ON_HIGH_LOAD: 'true'
      CRAWLER_TOTAL_MEMORY: 900
      CRAWLER_PAUSE_DURATION_LIMIT: 10
      TOTAL_DISK_SPACE: 1024
      CORS_ALLOWED_ORIGINS: https://www.movietracker.mom --- https://movietracker.mom --- http://movietracker.mom --- https://admin.movietracker.mom --- http://admin.movietracker.mom --- https://chat.movietracker.mom
      DOMAIN: movietracker.mom
    #    ports:
    #      - "3000:3000"
    deploy:
      resources:
        #also check --max_old_space_size in Dockerfile
        limits:
          cpus: "0.6"
          memory: 900M
        reservations:
          memory: 50M
    restart: always
    healthcheck:
      test: [ "CMD", "node", "healthcheck.js" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: "redis:7.2.3-alpine"
    network_mode: host
    env_file: ./env/.env
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - USE_OPTIMIZATION=true
    #    ports:
    #      - "6379:6379"
    volumes:
      - redis:/data
    entrypoint: /bin/sh -c "redis-server --latency-monitor-threshold 100 --maxmemory 80mb --maxmemory-policy allkeys-lfu --save 60 1 --appendonly yes --requirepass $$REDIS_PASSWORD"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 90M
        reservations:
          memory: 10M
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 20s

  telegrambot:
    image: ashkanaz2828/downloader_telegrambot
    network_mode: host
    depends_on:
      - api
    env_file: ./env/telegrambot.env
    environment:
      - API_URL=https://api.movietracker.mom
      - WEB_URL=https://movietracker.mom
      - MIN_IMDB_RATE=7
      - MIN_MAL_RATE=7
      - INITIAL_SLEEP_MINUTE=2
    volumes:
      - telegrambot
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
        reservations:
          memory: 10M
    restart: always

  adminpanel:
    image: ashkanaz2828/downloader_adminpanel
    network_mode: host
    depends_on:
      - api
      - torrent
    environment:
      - REACT_APP_BASE_URL=https://api.movietracker.mom
      - REACT_APP_TORRENT_BASE_URL=https://download.movietracker.mom
    #    ports:
    #      - "7070:7070"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
        reservations:
          memory: 10M
    restart: unless-stopped

  nginx:
    network_mode: host
    build: ./docker/nginx
    #    ports:
    #      - '80:80'
    depends_on:
      - api
      - chat
      - torrent
      - adminpanel
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 100M
        reservations:
          memory: 10M

  chat:
    image: ashkanaz2828/downloader_gochat
    depends_on:
      - redis
      - rabbitmq
    network_mode: host
    env_file: env/chatservice.env
    environment:
      PORT: 3002
      MAIN_SERVER_ADDRESS: api.movieTracker.mom
      CORS_ALLOWED_ORIGINS: https://www.movietracker.mom --- https://movietracker.mom --- http://movietracker.mom --- https://admin.movietracker.mom --- http://admin.movietracker.mom --- https://chat.movietracker.mom
      LOG_PANIC_TRACE: 'true'
      DOMAIN: movietracker.mom
      MALLOC_ARENA_MAX: 2
    #    ports:
    #      - "3002:3002"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: 150M
        reservations:
          memory: 20M
    restart: always

  rabbitmq:
    image: rabbitmq
    network_mode: host
    hostname: rabbitmq
    container_name: my-rabbitmq
    build:
      context: ./docker/rabbitmq
      dockerfile: ./Dockerfile
      network: host
    env_file: env/chatservice.env
    environment:
      - PORT=5672
#      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
#      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_ERLANG_COOKIE=unique-erlang-cookie
    #    ports:
    #      - "5672:5672"
    #      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 250M
        reservations:
          memory: 150M
    restart: always

  torrent:
    image: ashkanaz2828/downloader_torrent
    network_mode: host
    env_file: env/torrentservice.env
    environment:
      PORT: 3003
      MAIN_SERVER_ADDRESS: api.movieTracker.mom
      CORS_ALLOWED_ORIGINS: https://admin.movietracker.mom --- http://admin.movietracker.mom --- https://download.movietracker.mom
      LOG_PANIC_TRACE: 'true'
      DONT_CONVERT_MKV: 'true'
    volumes:
      - ./downloads:/app/downloads
    #    ports:
    #      - "3003:3003"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 300M
        reservations:
          memory: 50M
    restart: always

  postgresDb:
    image: postgres:16.0-alpine3.18
    env_file: ./env/.env
    network_mode: host
    container_name: downloader_postgres
    environment:
      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=downloader
    #    ports:
    #      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_min_messages=log"]
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 300M
        reservations:
          memory: 50M
    restart: always

volumes:
  redis:
    driver: local
  rabbitmq:
    driver: local
  telegrambot:
    driver: local
  pgdata:
    driver: local