version: '3.4'

services:
  api:
    image: downloader-api
    depends_on:
      - redis
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
      #target: "prod"
      network: host
    env_file: ./.env
    volumes:
      - .:/usr/app
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
#    ports:
#      - "3000:3000"
    deploy:
      resources:
        #also check --max_old_space_size in Dockerfile
        limits:
          cpus: 0.5
          memory: 1224M
        reservations:
          cpus: 0.2
          memory: 300M
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
