version: '3.4'

services:
  api:
    image: downloader-api
    depends_on:
      - redis
      - mailServer
      - remoteBrowser
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    env_file: ./.env
    volumes:
      - .:/usr/app
      - ./db-backups:/db-backups
    environment:
      NODE_ENV: production
      REDIS_URL: redis://127.0.0.1:6379
      REMOTE_BROWSER_ENDPOINT1: http://localhost:5000
      REMOTE_BROWSER_TABS_COUNT1: 3
      DISABLE_CRAWLER: 'false'
      CRAWLER_CONCURRENCY: 16
      PAUSE_CRAWLER_ON_HIGH_LOAD: 'true'
      CRAWLER_TOTAL_MEMORY: 900
      CRAWLER_PAUSE_DURATION_LIMIT: 10
      TOTAL_DISK_SPACE: 1024
      CORS_ALLOWED_ORIGINS: https://www.movietracker.mom --- https://movietracker.mom --- http://movietracker.mom --- https://admin.movietracker.mom --- http://admin.movietracker.mom
      MAILSERVER_HOST: localhost
      MAILSERVER_PORT: 587
      MAILSERVER_USERNAME: webmaster@movietracker.mom
    #    ports:
#      - "3000:3000"
    deploy:
      resources:
        #also check --max_old_space_size in Dockerfile
        limits:
          cpus: "0.6"
          memory: 900M
        reservations:
          memory: 50M
    restart: always
    healthcheck:
      test: [ "CMD", "node", "healthcheck.js" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: "redis:7.2.3-alpine"
    network_mode: host
    env_file: ./.env
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - USE_OPTIMIZATION=true
#    ports:
#      - "6379:6379"
    volumes:
      - redis:/data
    entrypoint: /bin/sh -c "redis-server --latency-monitor-threshold 100 --maxmemory 80mb --maxmemory-policy allkeys-lfu --save 60 1 --appendonly yes --requirepass $$REDIS_PASSWORD"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 90M
        reservations:
          memory: 10M
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 20s

  remoteBrowser:
    image: ashkanaz2828/downloader_remotebrowser
    network_mode: host
    env_file: ./remotebrowser.env
    environment:
      - NODE_ENV=production
      - CRAWLER_BROWSER_TAB_COUNT=3
      - TOTAL_MEMORY_AMOUNT=800
      - TOTAL_DISK_SPACE=2000
      - SERVER_NAME=remoteBrowser-vps-1
      - PRINT_ERRORS=true
      - CRAWLER_PAUSE_DURATION_LIMIT=30
      - DISABLE_UPLOAD_JOB=false
      - BLACKHOLE_FILE_SIZE_LIMIT=768
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
        reservations:
          memory: 50M
#    volumes:
#      - ./:/usr/app
#    ports:
#      - "5000:5000"
    restart: always

  telegrambot:
    image: ashkanaz2828/downloader_telegrambot
    network_mode: host
    depends_on:
      - api
    env_file: ./telegrambot.env
    environment:
      - API_URL=https://api.movietracker.mom
      - WEB_URL=https://movietracker.mom
    volumes:
      - telegrambot
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
        reservations:
          memory: 10M
    restart: always

  adminpanel:
    image: ashkanaz2828/downloader_adminpanel
    network_mode: host
    depends_on:
      - api
    environment:
      - REACT_APP_BASE_URL=https://api.movietracker.mom
#    ports:
#      - "7070:7070"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
        reservations:
          memory: 10M
    restart: unless-stopped

  website:
    image: ashkanaz2828/downloader_website
    network_mode: host
    depends_on:
      - api
    environment:
      - REACT_APP_BASE_URL=https://api.movietracker.mom
#    ports:
#      - "9090:9090"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
        reservations:
          memory: 10M
    restart: unless-stopped

  nginx:
    network_mode: host
    build: ./nginx
#    ports:
#      - '80:80'
    depends_on:
      - api
      - telegrambot
      - adminpanel
      - website
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 100M
        reservations:
          memory: 10M

  #more details in readme.md
  mailServer:
    image: boky/postfix
#    network_mode: host
    environment:
      - ALLOWED_SENDER_DOMAINS=movietracker.mom
    ports:
      - "587:587"
      - "25:25"
#    volumes:
#      - ./postfix/main.cf:/etc/postfix/main.cf
#      - ./postfix/virtual:/etc/postfix/virtual
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
        reservations:
          memory: 10M
    restart: always

  postgresDb:
    image: postgres:16.0-alpine3.18
    env_file: ./.env
    network_mode: service:api
    container_name: downloader_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=downloader
#    ports:
#      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_min_messages=log"]
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 300M
        reservations:
          memory: 50M
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres"]
#      interval: 10s
#      timeout: 5s
#      retries: 10
    restart: always

volumes:
  redis:
    driver: local
  telegrambot:
    driver: local
  pgdata:
    driver: local